# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f007fcb8d12c889ac92dd166d04b3fba1f58cbc09db5cedbafa4f0c0db9cebc83e2215cc9587e762dd9476c1653ef7b190172185370e2ed6b9736d4aac62d832

test:
  secret_key_base: 300b4b712dd2fb278e7b86d71d736966d8ac8a18822b87428516bb391f38dfc9a0cd872ec99acaf202e3aba1cb73e7b2edfa949b78c8afcfa0ef09b6cbabeed6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
